name: Release npm package

on:
  push:
    branches:
      - ft-set-up-semantic-release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn install --frozen-lockfile
      # - name: Set up JDK 1.8
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: 1.8
      # - name: Grant execute permission for gradlew
      #   run: cd android && chmod +x ./gradlew
      # - name: Check Lint
      #   run: cd android && sudo ./gradlew lintDebug
      # - name: Run tests
      #   run: cd android && sudo ./gradlew test
      # - name: Build with Gradle
      #   run: cd android && sudo ./gradlew build
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}